# -*- coding: utf-8 -*-
"""LVADSUSR103-Preethi_L-IA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qZJd16O3Ea545toWXOWv2Q5jQ8pvlaCX
"""

#1

import numpy as np
def grayscale_image(arr):
  grayscale_arr = np.array(ndmin = 3).shape(3,3)
  for x in arr:
    for y in x:
      for z in y:
        value = 0.2989 * arr[x][y][z]+0.5870* arr[x][y][z]+0.1140 * arr[x][y][z]
        grayscale_arr[x][y][z] = value

  return grayscale_arr

rgb_image = np.array([[[255,0,0],[0,255,0],[0,0,255]],
                      [[255,255,0],[255,0,255],[0,255,255]],
                      [[127,127,127],[200,200,200],[50,50,50]]])
g_arr = grayscale_image(rgb_image)
print(g_arr)
#print(rgb_image[0][0][0])

#2

#3
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr.flatten())

#4
import numpy as np
arr = np.array([[89,87,95],[98,90,88]])
df = pd.DataFrame(arr)
print(df)

#5

#6

#7
import pandas as pd
data = {
    'Name':['Alice','Bob','Charlie','David','Eve','Frank','Grace'],
    'Age':[25,30,35,40,45,50,55],
    'City':['New York','Los Angeles','Chicago','Houston','Phoenix','Miami','Boston'],
    'Department':['HR','IT','Finance','Marketing','Sales','IT','HR']
}
employee_df = pd.DataFrame(data)
list1 = employee_df[(employee_df['Age']<45) & (employee_df['Department'] != 'HR')]
print(employee_df[(employee_df['Age']<45) & (employee_df['Department'] != 'HR')])

#8

product_data = {
    'Product': ['Apples','Bananas','Cherries','Dates','Elderberies','Flour','Grapes'],
    'Category':['Fruit','Fruit','Fruit','Fruit','Fruit','Bakery','Fruit'],
    'Price':[1.20,0.50,3.00,2.50,4.00,1.50,2.00],
    'Promotion':[True,False,True,True,False,True,False]
}
product_df = pd.DataFrame(product_data)
avg_price = product_df[(product_df['Category']=='Fruit')]['Price'].agg('mean')
print(avg_price)

#9
import pandas as pd
employee_data = {
    'Employee':['Alice','Bob','Charlie','David'],
    'Department': ['HR','IT','Finance','IT'],
    'Manager' : ['John','Rachel','Emily','Rachel']
}
project_data = {
    'Employee': ['Alice','Charlie','Eve'],
    'Project' : ['P1','P3','P2']
}
employee_df = pd.DataFrame(employee_data)
project_df = pd.DataFrame(project_data)

new_dat = employee_df.merge()

#10

import pandas as pd
data = {
        'Department':['Electronics','Electronics','Clothing','Clothing','Home Goods'],
        'Salesperson':['Alice','Bob','Charlie','David','Eve'],
        'Sales':[70000,50000,30000,40000,60000]}
retail_df = pd.DataFrame(data)
#sales_data = retail_df['Sales'].agg(['sum'])
avg_sales = retail_df.groupby(['Department','Salesperson'])['Sales'].agg('mean')
rank = avg_sales.rank()
print(avg_sales.conactenate(rank))