# -*- coding: utf-8 -*-
"""Python_Internal_Assessment_1_Preethi_L.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aSz-UZ26S-Fnkpr2EKLYG3L2ebdndx-z
"""

#1
# Area of a rectangle

def area(length,width):
   area_of_rectangle = length * width
   return area_of_rectangle

length = int(input("Enter the length: "))
width = int(input("Enter the width: "))

print("Area of a rectangle is : ",area(length,width))

#2
#BMI

def BMI(weight,height):
    bmi = ( weight / height **2)
    return bmi

weight = int(input("Enter your weight: "))
height = int(input("Enter your height: "))

print("And your Body Mass Index(BMI) is : ",BMI(weight,height))

#3
#dictionary to print student scores and names

def input_dict():
   student_dict = {}
   number_of_students = int(input("Enter the students count: "))

   for i in range(number_of_students):
    student_name = input("Enter the student name {} :".format(i+1))
    score = int(input("Enter the {}\'s score : ".format(student_name)))
    student_dict[student_name] = score

   return student_dict

def main():
    student_dict = input_dict()
    print("Students Name and Scores : ")
    for student_name,score in student_dict.items():
      print("{} : {} ".format(student_name,score))

if __name__ == "__main__":
    main()

#4

name = input("Enter your name : ")
age = int(input("Enter your age: "))

if age < 18 :
  print("{} you're minor.".format(name))

elif age >= 18 and age <= 29:
  print("{} you're adult.".format(name))
elif age >=30 :
  print("{} you're senior.".format(name))
else :
  print("Give a valid age.")

#5

number = 50
print("Even numbers between 1 and 50 are ")
for i in range(1,number):
  if i%2 == 0 :
    print(i)

#6
#password

key = "Puppy"
while True:
  if()

#7

def calculate_average(list):
  avg = sum(list) / len(list)
  return avg

list = [1,2,3,4,5,6,7,8,9,10]
average = calculate_average(list)
print("The average of the list of numbers is {}: ".format(average))

#8

def count_of_vowels(word):
  str1 = (word.lower())
  x = 0
  for i in range(len(word)):
    if str1[i] == 'a' or str1[i] == 'e' or str1[i] == 'i' or str1[i] == 'o' or str1[i] == 'u':
      x+=1
  return x

word = input("Enter the word : ")
print("The count of vowels is : {}".format(count_of_vowels(word)))

#9

import datetime

print(datetime.datetime.now())

#10

try:
  num = int(input("Enter the value :"))
  num1 = 10
  num1+= num

except:
  print("Give the proper numeric value")


#finally:
 # print("Always give the correct value for data type")

#11

try :
   num = int(input("Enter the value: "))
except ValueError:
   print("Value error")

#12

def division(num1,num2):
  try:
    num = num1/num2

  except :
    print("Division by zero error")


num1 = 20
num2 = 0
num = division(num1,num2)

#13

f = open("/content/sample_data/new.txt","x")
f.write("Hello!,Python")
f.close()

#14

f= open("/content/sample_data/new.txt","r")
print(f.read())

#15
f = open("/content/sample_data/new.txt","a")
f.write("This is a new file")
f = open("/content/sample_data/new.txt","r")
print(f.read())